import type { Metadata } from 'next'
import './globals.scss'

export const metadata: Metadata = {
  title: 'Map App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" 
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" 
      integrity="sha512-Avb2QiuDEEvB4bZJYdft2mNjVShBftLdPG8FJ0V7irTLQ8Uo0qcPxh4Plq7G5tGm0rU+1SPhVotteLpBERwTkw=="
      crossOrigin="anonymous" 
      referrerPolicy="no-referrer" />
      </head>
      <body>
        {children}
      </body>
    </html>
  )
}
